language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
    - downloads
  python:
    - 2.7.15
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -c test-$PLONE_VERSION.x.cfg -N buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/coverage run bin/test
after_success:
  - bin/coveralls

